var BOOKS = [
  {
    "Image": "",
    "Title": "Pancho Rabbit and the Coyote",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "Immigration from Latin America",
    "Link": "https://www.goodreads.com/book/show/15842628-pancho-rabbit-and-the-coyote",
    "Grade Min ": "1",
    "Grade Max ": "4",
    "Textual Review ": "In this allegorical picture book, a young rabbit named Pancho eagerly awaits his papa’s return. Papa Rabbit traveled north two years ago to find work in the great carrot and lettuce fields to earn money for his family. When Papa does not return, Pancho sets out to find him. He packs Papa’s favorite meal—mole, rice and beans, a heap of warm tortillas, and a jug of aguamiel—and heads north. He meets a coyote, who offers to help Pancho in exchange for some of Papa’s food. They travel together until the food is gone and the coyote decides he is still hungry . . . for Pancho!",
    "Lowest Price": "$13.10",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1392244426l/15842628.jpg"
  },
  {
    "Image": "",
    "Title": "Crown: An Ode to a Fresh Cut ",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Black boys",
    "Link": "https://www.goodreads.com/book/show/34144489-crown?from_search=true&qid=IC95RSsXVK&rank=1",
    "Grade Min ": "3",
    "Grade Max ": "5",
    "Textual Review ": "“It’s not just a pleasure to read, it also does something important, and that is to show up and show out for black kids, black culture and black language. It’s about that time honored tradition for black folks of sitting in the chair at the barbershop, and the power of being seen as a black boy beyond stereotype out here in America. . . . Hook yourself up with this sweet and mighty book, both for you and your kids.” —Rebecca Carroll, Los Angeles Times Top Books of 2017",
    "Lowest Price": "$13.83",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/157/9781572842243.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Low Riders In Space",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "",
    "Link": "https://latinosinkidlit.com/2014/09/18/libros-latins-lowriders-in-space/",
    "Grade Min ": "3",
    "Grade Max ": "7",
    "Textual Review ": "Lupe Impala, El Chavo Flapjack, and Elirio Malaria love working with cars. You name it, they can fix it. But the team's favorite cars of all are lowriders—cars that hip and hop, dip and drop, go low and slow, bajito y suavecito. The stars align when a contest for the best car around offers a prize of a trunkful of cash—just what the team needs to open their own shop! ¡Ay chihuahua! What will it take to transform a junker into the best car in the universe? Striking, unparalleled art from debut illustrator Raul the Third recalls ballpoint-pen-and-Sharpie desk-drawn doodles, while the story is sketched with Spanish, inked with science facts, and colored with true friendship. With a glossary at the back to provide definitions for Spanish and science terms, this delightful book will educate and entertain in equal measure.",
    "Lowest Price": "$9.99",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/145/9781452121550.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Lucky Broken Girl",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "",
    "Link": "https://yawednesdays.com/2017/05/18/book-review-lucky-broken-girl-by-ruth-behar/",
    "Grade Min ": "4",
    "Grade Max ": "5",
    "Textual Review ": "In this unforgettable multicultural coming-of-age narrative—based on the author’s childhood in the 1960s—a young Cuban-Jewish immigrant girl is adjusting to her new life in New York City when her American dream is suddenly derailed. Ruthie’s plight will intrigue readers, and her powerful story of strength and resilience, full of color, light, and poignancy, will stay with them for a long time.   Ruthie Mizrahi and her family recently emigrated from Castro’s Cuba to New York City. Just when she’s finally beginning to gain confidence in her mastery of English—and enjoying her reign as her neighborhood’s hopscotch queen—a horrific car accident leaves her in a body cast and confined her to her bed for a long recovery. As Ruthie’s world shrinks because of her inability to move, her powers of observation and her heart grow larger and she comes to understand how fragile life is, how vulnerable we all are as human beings, and how friends, neighbors, and the power of the arts can sweeten even the worst of times.",
    "Lowest Price": "$6.56",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/039/9780399546457.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Juana and Lucas #1",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "",
    "Link": "https://www.goodreads.com/book/show/28686882-juana-lucas",
    "Grade Min ": "",
    "Grade Max ": "",
    "Textual Review ": "Juana loves many things: drawing, living in Bogotá, Colombia, and especially her dog, Lucas, the best amigo ever. She does not love wearing her itchy school uniform, solving math problems, or learning the English. Why is it so important to learn a language that makes so little sense? Hilarious, energetic, and utterly relatable, Juana will win over los corazones (the hearts) of readers everywhere.",
    "Lowest Price": "$5.83",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/153/9781536206395.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Niño Wrestles the World",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "Mexico",
    "Link": "https://latinosinkidlit.com/2014/01/30/libros-latinos-nino-wrestles-the-world/",
    "Grade Min ": "K",
    "Grade Max ": "2",
    "Textual Review ": "Señoras y señores, put your hands together for the fantastic, spectacular, one of a kind . . . Niño!  Fwap! Slish! Bloop! Krunch! He takes down his competition in a single move!  No opponent is too big a challenge for the cunning skills of Niño―popsicle eater, toy lover, somersault expert, and world champion lucha libre competitor!  Niño Wrestles the World is in English with Spanish vocabulary, and is a fun, colorful story about a boy wrestling with imaginary monsters (including an Olmec Head and La Llorona) and adversaries like his younger sisters. This is a joyful picture book about imagination, play, and siblings.",
    "Lowest Price": "$6.56",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/125/9781250062703.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Sulwe",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Colorism",
    "Link": "https://www.amazon.com/exec/obidos/ASIN/1534425365/ref=nosim/0sil8",
    "Grade Min ": "K",
    "Grade Max ": "2",
    "Textual Review ": "From Academy Award–winning actress Lupita Nyong’o comes a powerful, moving picture book about colorism, self-esteem, and learning that true beauty comes from within.  Sulwe has skin the color of midnight. She is darker than everyone in her family. She is darker than anyone in her school. Sulwe just wants to be beautiful and bright, like her mother and sister. Then a magical journey in the night sky opens her eyes and changes everything.  In this stunning debut picture book, actress Lupita Nyong’o creates a whimsical and heartwarming story to inspire children to see their own unique beauty.",
    "Lowest Price": "$13.13",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/153/9781534425361.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Dragon Pearl",
    "Geographic Origins ": "Asia (East and Central)",
    "Identity or Issue": "Korean",
    "Link": "https://www.amazon.com/exec/obidos/ASIN/136801335X/ref=nosim/0sil8",
    "Grade Min ": "3",
    "Grade Max ": "5",
    "Textual Review ": "THIRTEEN-YEAR-OLD MIN comes from a long line of fox spirits. But you'd never know it by looking at her. To keep the family safe, Min’s mother insists that none of them use any fox-magic, such as Charm or shape-shifting. They must appear human at all times.  Min feels hemmed in by the household rules and resents the endless chores, the cousins who crowd her, and the aunties who judge her. She would like nothing more than to escape Jinju, her neglected, dust-ridden, and impoverished planet. She’s counting the days until she can follow her older brother, Jun, into the Space Forces and see more of the Thousand Worlds.",
    "Lowest Price": "$5.83",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1517413544l/34966859.jpg"
  },
  {
    "Image": "",
    "Title": "We All Count",
    "Geographic Origins ": "Indigenous (Americas before colonization)",
    "Identity or Issue": "Cree",
    "Link": "https://www.goodreads.com/book/show/22334030-we-all-count",
    "Grade Min ": "K",
    "Grade Max ": "1",
    "Textual Review ": "We All Count: A Book of Cree Numbers is a sweet story on counting in the Cree language. On each page, the number is in English and then also in Cree, with the pronunciation right on that same page which made it great. This is a great book for a child learning how to count in another language and also is great in the fact that it teaches diversity for Native Americans. The pictures are appealing and any child can understand and relate to them. Personally, I believe that the title of the story, ‘We All Count’, means that Indigenous people count too, not just Americans.",
    "Lowest Price": "",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1401137440l/22334030.jpg"
  },
  {
    "Image": "",
    "Title": "Katie Fry, Private Eye #1: The Lost Kitten",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Black girls",
    "Link": "https://www.amazon.com/Scholastic-Reader-Level-Private-Kitten/dp/0545666724/ref=bseries_primary_1_0545666724",
    "Grade Min ": "1",
    "Grade Max ": "3",
    "Textual Review ": "Katie Fry may be little, but she's got a big brain, and she uses it to solve mysteries. So when she finds a very cute, VERY lost kitten named Sherlock, she decides to take his case. Can Katie track down the clues to find Sherlock's home?",
    "Lowest Price": "$3.99",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1434052136l/25710574._SX318_.jpg"
  },
  {
    "Image": "",
    "Title": "Katie Fry, Private Eye #2: The Missing Fox",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Black girls",
    "Link": "https://www.amazon.com/Missing-Fox-Scholastic-Reader-Level/dp/0545666759/ref=pd_sbs_14_1/136-4783733-6543317?_encoding=UTF8&pd_rd_i=0545666759&pd_rd_r=ea45a9bd-be27-4433-bc31-4af791a5f29d&pd_rd_w=tdL89&pd_rd_wg=RQo7s&pf_rd_p=7c0dad87-8a25-4c4f-9349-026039ea6cb3&pf_rd_r=AHB0J71HDE9675GCCAZV&psc=1&refRID=AHB0J71HDE9675GCCAZV",
    "Grade Min ": "1",
    "Grade Max ": "3",
    "Textual Review ": "Katie Fry may be little, but she's got a big brain, and she uses it to solve mysteries with her feline friend Sherlock. And they've got a new case. Katie's brother can't find his favorite stuffed animal anywhere. But with a nose for clues and a few good tips, Katie and Sherlock are hot on the fox's trail.",
    "Lowest Price": "$3.99",
    "Image URL": "http://prodimage.images-bn.com/pimages/9780545666756_p0_v1_s192x300.jpg"
  },
  {
    "Image": "",
    "Title": "Hula-Hoopin' Queen",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "",
    "Link": "https://www.amazon.com/Hula-Hoopin-Queen-Thelma-Lynne-Godin/dp/1620145790?SubscriptionId=AKIAILSHYYTFIVPWUY6Q&tag=duckduckgo-ffab-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=1620145790",
    "Grade Min ": "2",
    "Grade Max ": "5",
    "Textual Review ": "Kameeka loves hula hooping and is sure she can become the Hula-Hoopin’ Queen of 139th Street--but Mama reminds her that she has to help get ready for Miz Adeline’s birthday. After all, Miz Adeline took care of Mama and Kameeka when they each were babies. How will Kameeka ever get all these things done and get outside to beat her rival Jamara?",
    "Lowest Price": "$7.99",
    "Image URL": "http://3.bp.blogspot.com/-WRHSwyrI9IM/VI5CBwE608I/AAAAAAAAIhI/GlYXB5ya7Sw/s1600/hula%2Bhoopin%2Bqueen%2Binterior2.jpeg"
  },
  {
    "Image": "",
    "Title": "Alvin Ho: Allergic to Girls, School, and Other Scary Things (First book in a series)",
    "Geographic Origins ": "Asia (East and Central)",
    "Identity or Issue": "Vietnamese-American",
    "Link": "https://www.amazon.com/Alvin-Ho-Allergic-School-Things/dp/0375849300/ref=as_li_ss_tl?_encoding=UTF8&pd_rd_i=0375849300&pd_rd_r=8ef720ab-028f-11e9-a99c-25f61c0681a3&pd_rd_w=RnvMC&pd_rd_wg=Ioz0q&pf_rd_p=6725dbd6-9917-451d-beba-16af7874e407&pf_rd_r=3A6MCCTHS2AN93289TXW&psc=1&refRID=3A6MCCTHS2AN93289TXW&linkCode=sl1&tag=grekidboo-20&linkId=de4161b1b85c48f02aa5e593143c9a6b&language=en_US",
    "Grade Min ": "1 (chapter book)",
    "Grade Max ": "4",
    "Textual Review ": "(Review 1) The first book in the beloved and hilarious Alvin Ho chapter book series, which has been compared to Diary of a Wimpy Kid and is perfect for both beginning and reluctant readers.  Alvin, an Asian American second grader, is afraid of everything—elevators, tunnels, girls, and, most of all, school. He’s so afraid of school that, while he’ s there, he never, ever, says a word. But at home he’s a very loud superhero named Firecracker Man, a brother to Calvin and Anibelly, and a gentleman-in-training, so he can be just like his dad.  (Review 2) I purchased this book for a local elementary school library because it showed up on a list of top 20 read aloud books. I am now reading it to a class of second graders who find it, \"hilarious.\" It is a chapter book so an advanced read but it has captured their attention and imagination. The author, Lenore Look, has managed to weave the roots of our country's history as well as art, music, literature and famous historical figures into her very funny story line.",
    "Lowest Price": "$6.93",
    "Image URL": "http://3.bp.blogspot.com/-cnxCzNywxDc/UAmT_2p-wbI/AAAAAAAAFM8/NWFmkAN5NU8/s1600/AlvinHo.jpg"
  },
  {
    "Image": "",
    "Title": "Big Red Lollipop",
    "Geographic Origins ": "South Asia",
    "Identity or Issue": "Pakistani",
    "Link": "https://www.amazon.com/Big-Red-Lollipop-Rukhsana-Khan/dp/0670062871",
    "Grade Min ": "K",
    "Grade Max ": "4",
    "Textual Review ": "About a Pakistani family living in the West and the children, especially eldest sister, Rubina, navigating cultural differences with their traditional mother. I can't count how many times my four year old daughter asked us to read her this book. The story is a pitch perfect account of the dynamics in an immigrant household. Rubina is so excited about getting an invitation to a birthday party that she runs all the way home from school. When she asks her mom if she can go, her little sister, Sana, screams that she wants to go to.",
    "Lowest Price": "$13.42",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/067/9780670062874.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "How I Became a Ghost (Book 1 in the How I Became A Ghost Series)",
    "Geographic Origins ": "Indigenous (Americas before colonization)",
    "Identity or Issue": "Choctaw",
    "Link": "https://www.goodreads.com/book/show/17901341-how-i-became-a-ghost",
    "Grade Min ": "4",
    "Grade Max ": "7",
    "Textual Review ": "Written by Tim Tingle, himself a member of the Choctaw Nation of Oklahoma and whose grandfather marched the Trail of Tears, How I Became a Ghost: A Choctaw Trail of Tears Story  (2013) is a middle-grade historical fiction account of a young boy in  the Choctaw nation and his death on the tragic Trail of Tears.  The  first in a trilogy, the book is well regarded for its Native American  perspective. It won the 2014 American Indian Youth Literature Award and  was on Kirkus Review’s list of Best Books of 2013—Making History Come Alive.  Tingle manages to keep a very depressing story lighter than it ought to be. Isaac is a compelling narrator. There are moments of humor and inspiration mingled within the sadness and devastation. Tingle also refuses to fit his characters into clichés, with small sympathetic moments for the soldiers presenting a balanced, holistic portrayal of an ugly moment in American history.  Written for a younger audience, How I Became a Ghost: A Choctaw Trail of Tears Story tells a harrowing, often violent story without being gratuitous. At fewer than 200 pages, it is also an incredibly fast, minimalistic read that is accessible for young readers in middle school.",
    "Lowest Price": "",
    "Image URL": "http://3.bp.blogspot.com/-7diUmed7UOk/U8y80cVLEFI/AAAAAAAABNw/PPyJvEvpK7s/s1600/how_i_became_a_ghost.jpg"
  },
  {
    "Image": "",
    "Title": "Bayou Magic",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Black girls",
    "Link": "https://www.goodreads.com/book/show/23197281-bayou-magic?from_search=true&qid=fMTzexL2lD&rank=1",
    "Grade Min ": "4",
    "Grade Max ": "5",
    "Textual Review ": "Maddy is about to spend her first summer with her grandmother, Grandmère, a prospect that makes her nervous since all of her older sisters say that she is weird and that the bayou is boring. Nevertheless, off Maddy goes to Bon Temps, LA. At first, she is unsure of what to think of Grandmère, and then she discovers that Grandmère tells wonderful stories about their family past: stories of Mami Watta and Membe. Then she introduces Maddy to Bear, a boy who lives nearby with his father who works on an oil platform. At first, the summer is perfect, and Maddy is able to learn from Grandmère and explore the bayou. But then she starts having bad dreams, and Bear disappears for days on end. What has happened to Maddy's friend? And do her bad dreams mean something is about to happen? If so, will Maddy be able to save Bon Temps?  This story is a wonderful mix of folk stories and childhood fantasy, with a healthy dose of environmental realism. This book is recommended for imaginative children who don't mind a bit of realism in their fantasy. Due to some sensitive topics, it is recommended that children be around 4th or 5th grade before reading this story.",
    "Lowest Price": "$5.83",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/031/9780316224840.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Paper Wishes",
    "Geographic Origins ": "Asia (East and Central)",
    "Identity or Issue": "Japanese. WW2 internment. ",
    "Link": "https://www.goodreads.com/book/show/25667444-paper-wishes?ac=1&from_search=true&qid=QczGql60AD&rank=1",
    "Grade Min ": "3",
    "Grade Max ": "5",
    "Textual Review ": "In this work of historical fiction by Lois Sepahban, 10-year-old Manami is forced to leave her home after the attack on Pearl Harbor—her Japanese American family is relocated from Bainbridge Island, near Seattle, to an internment camp in the California desert. When her dog is taken from her in the process, Manami stops talking. A good introduction to the tough subject of Japanese internment—and the personal and social cost of intolerance.",
    "Lowest Price": "$5.83",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1433641608l/25667444.jpg"
  },
  {
    "Image": "",
    "Title": "Amal Unbound",
    "Geographic Origins ": "South Asia",
    "Identity or Issue": "Pakistan. Patriarchy.",
    "Link": "https://www.penguinrandomhouse.com/books/533523/amal-unbound-by-aisha-saeed/",
    "Grade Min ": "3",
    "Grade Max ": "5",
    "Textual Review ": "True-to-life story of unjust power dynamics in a poor Pakistani village with a palpable sense of dread regarding the fate of the inquisitive, industrious, poetry-loving titular character. . . . Amal’s experience navigating an unfamiliar social hierarchy in the landlord’s lavish estate exposes her to pervasive gender inequities and unfair labor practices. . . . Saeed’s eloquent, suspenseful, eye-opening tale offers a window into the contemporary practice of indentured servitude and makes a compelling case for the power of girls’ education to transform systemic injustice.",
    "Lowest Price": "$6.56",
    "Image URL": "https://images1.penguinrandomhouse.com/cover/9780399544699"
  },
  {
    "Image": "",
    "Title": "Amina's Voice",
    "Geographic Origins ": "South Asia",
    "Identity or Issue": "Pakistani-American Muslim girl",
    "Link": "https://www.amazon.com/Aminas-Voice-Hena-Khan/dp/1481492071/ref=sr_1_1?crid=2KBG1Y3QI7NPJ&keywords=amina%27s+voice&qid=1578001121&s=books&sprefix=amina%27s+v%2Cstripbooks%2C194&sr=1-1",
    "Grade Min ": "3",
    "Grade Max ": "5",
    "Textual Review ": "A Pakistani-American Muslim girl struggles to stay true to her family’s vibrant culture while simultaneously blending in at school after tragedy strikes her community in this “compassionate, timely novel” (Booklist, starred review) from the award-winning author of It’s Ramadan, Curious George and Golden Domes and Silver Lanterns.",
    "Lowest Price": "$5.83",
    "Image URL": "https://www.thereadingwarehouse.com/thumb.php?src=products/148/9781481492072.jpg&wmax=400&hmax=400"
  },
  {
    "Image": "",
    "Title": "Esperanza Rising",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "Mexican. Immigration.",
    "Link": "https://www.amazon.com/Esperanza-Rising-McDougal-Littell-Library/dp/043912042X/ref=sr_1_1?crid=2VR7LOCS4GYSJ&keywords=esperanza+rising&qid=1578001478&s=books&sprefix=esperanza%2Cstripbooks%2C191&sr=1-1",
    "Grade Min ": "5",
    "Grade Max ": "5",
    "Textual Review ": "Esperanza believed her life would be wonderful forever. She would always live on her family's ranch in Mexico. She would always have fancy dresses and a beautiful home filled with servants. Papa and Abuelita would always be with her.  But a sudden tragedy shatters her world and Esperanza and Mama flee to California, where they settle in a camp for Mexican farm workers. Esperanza isn't ready for the hard labor, financial struggles brought on by the Great Depression, and lack of acceptance she now faces. When Mama gets sick, and a strike for better working conditions threatens to uproot their new life, Esperanza must find a way to rise above her difficult circumstances — because Mama's life and her own depend on it.",
    "Lowest Price": "$5.83",
    "Image URL": "https://www.scholastic.com/content5/media/products/18/9780439120418_mres.jpg"
  },
  {
    "Image": "",
    "Title": "The First Rule of Punk",
    "Geographic Origins ": "Latin America after colonization",
    "Identity or Issue": "Mexican-American.",
    "Link": "https://www.amazon.com/First-Rule-Punk-Celia-P%C3%A9rez/dp/0425290425/ref=sr_1_1?keywords=the+first+rule+of+punk&qid=1578002332&s=books&sr=1-1",
    "Grade Min ": "4",
    "Grade Max ": "5",
    "Textual Review ": "When your mom is SuperMexican life is tough. And when SuperMexican announces that you are moving with her for two years from Gainesville, Florida to Chicago, Illinois, away from your beloved father and friends, you’re allowed to get peeved. The trouble is that Malu doesn’t think she has ANYTHING in common with her mom. Malu doesn’t like cilantro, loves punk music, makes Zines, and has absolutely no interest in connecting with her Mexican roots, so to speak. Still, Chicago isn’t quite what she expected. And when the chance comes up to put together her own ragtag punk band, she finds that sometimes you follow the rules, sometimes you break the rules, and sometimes it’s a lot more fun to just go on out and make your own rules.  First and foremost, Ms. Perez makes sure right from the start that kids reading this book will find it fun. That's why right after the very first chapter we get our first glimpse at Malu's Zines.",
    "Lowest Price": "$6.56",
    "Image URL": "http://100scopenotes.com/files/2017/07/The-First-Rule-of-Punk-356x550.jpg"
  },
  {
    "Image": "",
    "Title": "The House That Lou Built",
    "Geographic Origins ": "Asia (East and Central)",
    "Identity or Issue": "Filipino-American",
    "Link": "https://www.goodreads.com/book/show/29752051-the-house-that-lou-built?ac=1&from_search=true&qid=zyCO3OaXYk&rank=1",
    "Grade Min ": "4",
    "Grade Max ": "5",
    "Textual Review ": "Lou Bulosan-Nelson is going to build her dream. She shares a room with her mom in her grandmother's house in San Francisco, and longs for a place of her own where she can escape her lovable but large extended Filipino family. Lou has a talent for woodshop class and creating projects, and plans to build a tiny house, 100 square feet, all her own, on land that she inherited from her dad, who died before she was born. Then Lou discovers it's not so easy to build one, but she won't give up on her dream—and her friends and family won’t either. This heartwarming coming-of-age story explores culture and family, forgiveness and friendship, and what makes a house a true home.",
    "Lowest Price": "$5.10",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1510801132l/29752051._SY475_.jpg"
  },
  {
    "Image": "",
    "Title": "The Great Cake Mystery (Precious Ramotswe's Very First Cases #1)",
    "Geographic Origins ": "Africa",
    "Identity or Issue": "Botswana",
    "Link": "https://www.goodreads.com/book/show/13343102-the-great-cake-mystery?ac=1&from_search=true&qid=eaNHDAMKS9&rank=2",
    "Grade Min ": "2",
    "Grade Max ": "5",
    "Textual Review ": "The Great Cake Mystery introduces young readers to the lovely setting of Botswana and a precocious young girl named Precious who likes to figure things out. Although she thinks it may be many years before she’ll have a mystery to solve, it turns out that someone in her school is eating people’s snacks and she may just be able to figure out who has done it. With her father’s encouragement and her own careful logic, a detective is born in Botswana.",
    "Lowest Price": "$5.10",
    "Image URL": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1333584953l/13343102.jpg"
  }
]
